Repository caicloud/loadbalancer-controller, pull requests merged in 2019-04, with the labels that each got.

#82 [CPS-1466] fix: set lb unavailable when provider-azure pod can't startup
  pkg/provider/providers/azure/azure.go
  pkg/provider/providers/azure/status.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#84 fix(evict): delete pod if it MatchNodeSelector failed
  pkg/provider/providers/ipvsdr/status.go
  pkg/proxy/proxies/nginx/status.go
  pkg/util/lb/pod.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#86 refactor(node): simplify node controller's code
  pkg/controller/loadbalancer.go
  pkg/controller/nodes.go
  pkg/controller/utils.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#96 feat(nginx): make it possible to run nginx without hostnetwork
  Gopkg.lock
  Gopkg.toml
  build/controller/Dockerfile
  pkg/kubelab/apps/v1/deployment.go
  pkg/proxy/nginx/ingress.go
  vendor/github.com/InVisionApp/conjungo/LICENSE
  vendor/github.com/InVisionApp/conjungo/merge.go
  vendor/github.com/InVisionApp/conjungo/mfunc.go
  vendor/github.com/konsorten/go-windows-terminal-sequences/LICENSE
  vendor/github.com/konsorten/go-windows-terminal-sequences/sequences.go
  vendor/github.com/konsorten/go-windows-terminal-sequences/sequences_dummy.go
  vendor/github.com/sirupsen/logrus/LICENSE
  vendor/github.com/sirupsen/logrus/alt_exit.go
  vendor/github.com/sirupsen/logrus/doc.go
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/formatter.go
  vendor/github.com/sirupsen/logrus/hooks.go
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_check_appengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_bsd.go
  vendor/github.com/sirupsen/logrus/terminal_check_js.go
  vendor/github.com/sirupsen/logrus/terminal_check_notappengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_unix.go
  vendor/github.com/sirupsen/logrus/terminal_check_windows.go
  vendor/github.com/sirupsen/logrus/terminal_notwindows.go
  vendor/github.com/sirupsen/logrus/terminal_windows.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/writer.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL
