Repository caicloud/loadbalancer-controller, pull requests merged in 2019-09, with the labels that each got.

#112 feat: add server-tokens for configmap
  pkg/proxy/nginx/config.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#114 feat: improve compatibility for CLI args
  cmd/controller/app/cmd.go
  cmd/controller/app/options/options.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#116 fix: keep unrecognized configuration when ensure lb configmap
  pkg/proxy/nginx/config.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#115 feat: format project
  .caimake/update.sh
  .golangci.yml
  Makefile
  Makefile.expansion
  build/controller/Dockerfile
  hack/read_cpus_available.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#118 refactor: fix lint code
  Makefile
  cmd/controller/app/cmd.go
  hack/license/main.go
  pkg/config/config.go
  pkg/controller/loadbalancer.go
  pkg/controller/nodes.go
  pkg/kubelab/apps/interface.go
  pkg/kubelab/apps/v1/deployment.go
  pkg/kubelab/core/interface.go
  pkg/kubelab/core/v1/pod.go
  pkg/kubelab/import_known_versions.go
  pkg/kubelab/meta/interface.go
  pkg/provider/azure/azure.go
  pkg/provider/azure/status.go
  pkg/provider/ipvsdr/ipvsdr.go
  pkg/proxy/nginx/config.go
  pkg/proxy/nginx/default.go
  pkg/proxy/nginx/nginx.go
  pkg/toleration/toleration.go
  pkg/util/lb/deployment.go
  pkg/util/lb/event_handler.go
  pkg/util/lb/lb.go
  pkg/util/lb/pod.go
  pkg/util/taints/taints.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M
