Repository caicloud/loadbalancer-controller, pull requests merged in 2019-11, with the labels that each got.

#127 fix: not specify priority for none-critical pod on v2.10.0
  release/loadbalancer-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#128 fix(net): update controller and provider resources limits and requests
  pkg/provider/azure/azure.go
  pkg/provider/ipvsdr/ipvsdr.go
  pkg/proxy/nginx/ingress.go
  release/loadbalancer-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#130 fix error reported by golangci-lint v1.20.1
  pkg/controller/nodes.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#132 feat(azure): [KAIDE-54,KAIDE-56,KAIDE-57]CLONE-Upgrade Project KAIDE from 2.8.3 to 2.9.1
  pkg/provider/azure/azure.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#131 feat: support custom configs for lb
  pkg/proxy/nginx/config.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L
