Repository caicloud/loadbalancer-controller, pull requests merged in 2019-12, with the labels that each got.

#134 fix: only labeled external cm is selected
  pkg/proxy/nginx/config.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#135 fix: set ingress loglevel v=3
  pkg/proxy/nginx/ingress.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#136 fix: enable use-forwarded-headers by default
  pkg/proxy/proxies/nginx/config.go
Labels: caicloud-cla: yes, release-note-none, size/XS

#137 fix: increase resource limits and requests
  pkg/provider/azure/azure.go
  pkg/provider/ipvsdr/ipvsdr.go
  release/loadbalancer-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S
