Repository caicloud/loadbalancer-controller, pull requests merged in 2020-04, with the labels that each got.

#159 fix: sync lb crd with the definition in vaquita
  pkg/controller/loadbalancer.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#160 chore: update vendor to add NodeStatus
  go.mod
  go.sum
  vendor/github.com/caicloud/clientset/customclient/clientset.go
  vendor/github.com/caicloud/clientset/customclient/scheme/register.go
  vendor/github.com/caicloud/clientset/customclient/typed/alerting/v1beta1/alerting_client.go
  vendor/github.com/caicloud/clientset/customclient/typed/alerting/v1beta1/alertingrule.go
  vendor/github.com/caicloud/clientset/customclient/typed/alerting/v1beta1/alertingsubrule.go
  vendor/github.com/caicloud/clientset/customclient/typed/alerting/v1beta1/doc.go
  vendor/github.com/caicloud/clientset/customclient/typed/alerting/v1beta1/generated_expansion.go
  vendor/github.com/caicloud/clientset/custominformers/alerting/interface.go
  vendor/github.com/caicloud/clientset/custominformers/alerting/v1beta1/alertingrule.go
  vendor/github.com/caicloud/clientset/custominformers/alerting/v1beta1/alertingsubrule.go
  vendor/github.com/caicloud/clientset/custominformers/alerting/v1beta1/interface.go
  vendor/github.com/caicloud/clientset/custominformers/generic.go
  vendor/github.com/caicloud/clientset/listers/alerting/v1beta1/alertingrule.go
  vendor/github.com/caicloud/clientset/listers/alerting/v1beta1/alertingsubrule.go
  vendor/github.com/caicloud/clientset/listers/alerting/v1beta1/expansion_generated.go
  vendor/github.com/caicloud/clientset/pkg/apis/alerting/v1beta1/alertingrule.go
  vendor/github.com/caicloud/clientset/pkg/apis/alerting/v1beta1/alertingsubrule.go
  vendor/github.com/caicloud/clientset/pkg/apis/alerting/v1beta1/doc.go
  vendor/github.com/caicloud/clientset/pkg/apis/alerting/v1beta1/register.go
  vendor/github.com/caicloud/clientset/pkg/apis/alerting/v1beta1/types.go
  vendor/github.com/caicloud/clientset/pkg/apis/alerting/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/caicloud/clientset/pkg/apis/alerting/v1beta1/zz_generated.defaults.go
  vendor/github.com/caicloud/clientset/pkg/apis/loadbalance/v1alpha2/types.go
  vendor/github.com/caicloud/clientset/pkg/apis/loadbalance/v1alpha2/zz_generated.deepcopy.go
  vendor/github.com/caicloud/clientset/pkg/apis/resource/v1beta1/cluster.go
  vendor/github.com/caicloud/clientset/pkg/apis/resource/v1beta1/const.go
  vendor/github.com/caicloud/clientset/pkg/apis/resource/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#161 upgrade crd apiversion to v1 for k8s 1.17+
  pkg/controller/loadbalancer.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#162 [CPS-6637]chore(*): bump kubernetes version to 1.17.5
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/util/connrotation/connrotation.go
  vendor/k8s.io/kubernetes/pkg/apis/autoscaling/BUILD
  vendor/k8s.io/kubernetes/pkg/apis/autoscaling/helpers.go
  vendor/k8s.io/kubernetes/pkg/apis/autoscaling/v1/BUILD
  vendor/k8s.io/kubernetes/pkg/apis/autoscaling/v1/conversion.go
  vendor/k8s.io/kubernetes/pkg/apis/autoscaling/v2beta1/BUILD
  vendor/k8s.io/kubernetes/pkg/apis/autoscaling/v2beta1/conversion.go
  vendor/k8s.io/kubernetes/pkg/apis/autoscaling/v2beta1/zz_generated.conversion.go
  vendor/k8s.io/kubernetes/pkg/apis/autoscaling/v2beta2/BUILD
  vendor/k8s.io/kubernetes/pkg/apis/autoscaling/v2beta2/conversion.go
  vendor/k8s.io/kubernetes/pkg/apis/autoscaling/v2beta2/zz_generated.conversion.go
  vendor/k8s.io/kubernetes/pkg/apis/core/v1/conversion.go
  vendor/modules.txt
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL
