Repository caicloud/loadbalancer-controller, pull requests merged in 2020-03, with the labels that each got.

#147 optimize: use internal http backend to replace default-http-backend
  pkg/config/config.go
  pkg/proxy/nginx/default.go
  pkg/proxy/nginx/ingress.go
  pkg/proxy/nginx/nginx.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#152 [CPS-6115]fix: redefine Registry struct in package of plugin
  Gopkg.lock
  Gopkg.toml
  pkg/plugin/plugin.go
  vendor/github.com/zoumo/golib/LICENSE
  vendor/github.com/zoumo/golib/register/register.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#154 [CPS-6036]fix: mount xtables file to ipvsdr deployment
  pkg/provider/ipvsdr/ipvsdr.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#153 [CPS-6049]build: switch to go mod
  Gopkg.lock
  Gopkg.toml
  Makefile
  go.mod
  go.sum
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#156 upgrade golang version to 1.13.6 & upgrade golangci-lint
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#158 chore: update nginx-ingress-controller version
  release/loadbalancer-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS
